printWidth: 150
tabWidth: 4
useTabs: true
semi: false
singleQuote: true
quoteProps: as-needed
jsxSingleQuote: true
trailingComma: none
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: avoid
svelteSortOrder: scripts-markup-styles
svelteStrictMode: false
svelteBracketNewLine: true
